#This workflow will isntall Python dependencies and run tests

name: GrIS_vel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov pandas scikit-learn numpy matplotlib
          if [ -f requirements.txt]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest 
             
