name: Coverage

on:
  push:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install pytest pytest-cov pandas scikit-learn numpy matplotlib
          python -m pip install .[dev]

      - name: Run coverage
        run: |
          pytest --cov-config=.coveragerc --cov=./Tests --cov-report=xml
          cat coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: coverage.xml
